# Header
menu:
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: true
widgets:
- self_introduction
- recent_posts
- category
- tagcloud

# Miscellaneous
google_analytics: UA-62644130-1
favicon: /favicon.ico
twitter: https://twitter.com/Mollykannn
fb_admins:
fb_app_id: 1587998741464898

